[Content]
Packages=
    curl
    wget
    vim
    nano
    tmux
    htop
    rsync
    unzip
    dnsutils
    tcpdump
    traceroute
    docker.io
    docker-compose
    nftables
    bridge-utils
    vlan
    smartmontools
    restic
    netdata
    cockpit
