[Content]
Packages=
    systemd
    systemd-sysv
    systemd-timesyncd
    dbus
    linux-image-amd64
    initramfs-tools
    openssh-server
    apt
    sudo
    iproute2
    iputils-ping
    ca-certificates
    locales
    tzdata
    systemd-boot
    systemd-boot-efi
    mtools
    dosfstools
