[Output]
Format=directory
ImageId=arivon-os-cloud
OutputDirectory=./output/cloud
Output=arivon-os-cloud-0.1.0

[Content]
Packages=
    systemd
    linux-image-amd64
    openssh-server
    apt
    sudo
    iproute2
    ca-certificates
    locales
    tzdata
    cloud-init
    grub-efi-amd64-bin
    grub-pc-bin
    mtools
    dosfstools

[Output]
Bootable=yes
Bootloader=grub
UKI=yes
