[Content]
Profiles=minimal
Packages=
    systemd
    linux-image-amd64
    openssh-server
    apt
    sudo
    iproute2
    ca-certificates
    locales
    tzdata
    grub-efi-amd64-bin
    grub-pc-bin
    mtools
    dosfstools
