[Distribution]
Distribution=debian
Release=trixie

[Output]
Format=disk
OutputDirectory=output
ImageId=arivon-os
Bootable=yes
Bootloader=grub

[Content]
Packages=
    systemd
    systemd-sysv
    systemd-timesyncd
    dbus
    linux-image-amd64
    initramfs-tools
    openssh-server
    apt
    sudo
    iproute2
    iputils-ping
    ca-certificates
    locales
    tzdata
    grub-efi-amd64-bin
    grub-pc-bin
    mtools
    dosfstools
